---

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
  when: cmd_distribution != "cmd-one"

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
    disablerepo: CMD-ONE*
  when: cmd_distribution == "cmd-one"

- set_fact:
    complete_pkglist: "{{ logfile | dirname }}/complete.pkgs"
    excluded_pkglist: "{{ logfile | dirname }}/excluded.pkgs"

- name: Get all the packages from UMD/CMD repositories
  shell: /usr/bin/repoquery --qf="%{name}" --disablerepo=* --enablerepo={{ distribution|upper }}-*-candidate* -a
  register: pkglist

- name: Get all the packages from UMD/CMD repositories in Scientific6
  shell: /usr/bin/repoquery --qf="%{name}" --disablerepo=* --enablerepo={{ distribution|upper }}-*-candidate* -a --archlist=x86_64
  register: pkglist

- name: Save package list in file
  copy: 
    content: "{{ pkglist.stdout }}"
    dest: "{{ complete_pkglist }}"

- name: Save excluded packages in file
  copy:
    src: "{{ role_path }}/files/exclude.pkgs"
    dest: "{{ excluded_pkglist }}" 

- name: Save unmatched packages
  shell: "/bin/fgrep -v -f {{ excluded_pkglist }} {{ complete_pkglist }}"
  register: pkglist_unmatched

- name: Save package list in file
  copy: 
    content: "{{ pkglist_unmatched.stdout }}"
    dest: "{{ logfile }}"

- name: Install all the packages from CMD repositories
  shell: yum -y install $(cat {{ logfile }})
