---

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Get all the packages from CMD repositories
  shell: /usr/bin/repoquery --disablerepo=* --enablerepo=CMD-OS-*-candidate* -a
  register: pkglist

- name: Save package list in file
  copy: content="{{ pkglist.stdout }}" dest={{ logfile }} owner=centos group=centos

- name: Stat file
  stat:
    path: "{{ logfile }}"
  register: sym

- debug:
    msg: "Path exists and isn't a symlink"
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- shell: /bin/ls -l {{ logfile | dirname }}
  register: lsdir

- debug:
    msg: "LS command: {{ lsdir.stdout}}"

- name: Install all the packages from CMD repositories
  shell: yum -y install $(cat {{ logfile }})
