---

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Install all the packages from UMD repositories
  shell: /usr/bin/repoquery --disablerepo=* --enablerepo=UMD* -a | xargs yum -y install > logs/package_details.log
